name: physion_acquisition
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - numpy<1.19.0
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - ruamel
  - ruamel.yaml
  - pathlib
  - jupyter
  - pip:
    - pyqt5
    - pyqt5.sip
    - h5py==2.10.0
    - pyqtgraph
    - pynwb
    - nidaqmx
    - psychopy==2021.1.1
    - git+https://github.com/yzerlaut/physion