name: physion
channels:
  - conda-forge
dependencies:
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - tbb
  - numpy<1.19.0
  - numba<0.50.0
  - matplotlib
  - scipy
  - scikit-learn
  - ruamel
  - ruamel.yaml
  - pathlib
  - jupyter
  - pip:
    - pyqt5
    - pyqt5.sip
    - h5py==2.10.0
    - rastermap>0.1.0
    - tifffile
    - scanimage-tiff-reader>=1.4.1
    - pyqtgraph
    - importlib-metadata
    - paramiko
    - pynwb
    - sbxreader
    - suite2p
    - nidaqmx
    - psychopy==2021.1.1
    - scikit-video
    - pygame
    - opencv-python    
    - git+https://github.com/yzerlaut/datavyz
    - git+https://github.com/yzerlaut/physion